# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

lane :beta do
  build_app(export_method: "development")
  # crashlytics(
  #   api_token: "b6bff7f9d892076fe30d9fc608e2c42dc9376453",
  #   build_secret: "a04a63ce0bf7d1ee9858277a29bfea6cd6ca7440dcb00031c456a1d49c791341"
  # )
end
